# PYCZMQ

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

# Perform regression test build against latest dependencies

# Command to install Python dependencies
install: pip install --use-mirrors -r requirements.txt

# Commands to install C library dependencies

# sodium
- git clone git://github.com/jedisct1/libsodium.git
- cd libsodium
- ./autogen.sh
- ./configure
- make check
- sudo make install
- sudo ldconfig
- cd ..

# zmq
- git clone git://github.com/zeromq/libzmq.git
- cd libzmq
- ./autogen.sh
- ./configure && make check
- sudo make install
- sudo ldconfig
- cd ..

# czmq
- git clone git://github.com/zeromq/czmq.git
- cd czmq
- ./autogen.sh
- ./configure && make check
- sudo make install
- sudo ldconfig
- cd ..



# Test and install PYCZMQ
script:
  - nosetests
  - python setup.py install

